/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '2/20/22, 8:41 PM' 
 * Generated by 'nzh16001' 
 * Generated on server 'CTX-VDA-MSB-S06.GROVE.AD.UCONN.EDU' 
 * Generated on SAS platform 'X64_SRV19 WIN' 
 * Generated on SAS version '9.04.01M7P08052020' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko' 
 * Generated on web client 'http://localhost:57719/main?locale=en_US&zone=GMT-05%253A00&sutoken=%257BE79B737D-EC55-4FE7-84CD-DCECED2E7624%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=STSM.'NY PRICE TEMP DAILY'n out=Work.preProcessedData;
	by date1;
run;


options mprint;

/* Specify the number of timepoints for holdback across the program with &nhold. */


%let nhold=365;

/* This reads in the external file containing the actual macros and submits it when */
/* this statement is submitted. */

%include "P:\Forecasting-datasets-OPIM5671\macros2.sas" / source2;

%accuracy_prep(indsn=Work.preProcessedData, series=avgprice, timeid=date1, 
    numholdback=&nhold);


ods select none;


proc arima data=Work.preProcessedData plots
     (only)=(series(corr crosscorr) residual(corr normal) 
		forecast(forecast forecastonly)) out=work.out0001;
	identify var=avgprice crosscorr=(avgtemp 'weather dummy'n);
	estimate p = 4 q = 6
	input=(4 $ avgtemp 'weather dummy'n) method=ML outest=work.outest0001 
		outstat=work.outstat0001;
	forecast lead=365 back=365 alpha=0.05 id=date1 interval=day printall;
	outlier;
	run;
quit;

ods select all;

%accuracy(indsn=work.out0001, timeid=date1, series=avgprice, 
    numholdback=&nhold);
run;

proc delete data=Work.preProcessedData;
run;