/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '20/02/2022 22:26' 
 * Generated by 'u59395253' 
 * Generated on server 'ODAWS01-USW2.ODA.SAS.COM' 
 * Generated on SAS platform 'Linux LIN X64 3.10.0-1062.9.1.el7.x86_64' 
 * Generated on SAS version '9.04.01M6P11072018' 
 * Generated on browser 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.80 Safari/537.36' 
 * Generated on web client 'https://odamid-usw2.oda.sas.com/SASStudio/main?locale=en_GB&zone=GMT-05%253A00&ticket=ST-96054-SpefZCkqCXbkcbFfbBIv-cas' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=PROJ.NEWYORK2 out=Work.preProcessedData;
	by date1;
run;


options mprint;

/* Specify the number of timepoints for holdback across the program with &nhold. */


%let nhold=365;

/* This reads in the external file containing the actual macros and submits it when */
/* this statement is submitted. */

%include "&programloc/Macros2.sas" / source2; 

%accuracy_prep(indsn=Work.preProcessedData, series=avgprice, timeid=date1, 
    numholdback=&nhold);


ods select none;

proc arima data=Work.preProcessedData plots
     (only)=(series(corr crosscorr) residual(corr normal) 
		forecast(forecast forecastonly) ) out=work.mintempavgprice;
	identify var=avgprice crosscorr=('weather dummy'n mintemp);
	estimate p = 4 q = 6
	input=('weather dummy'n 1 $ mintemp 2 $ mintemp) method=ML 
	outest=work.outest_new outstat=work.outstat_new;
	forecast lead=365 back=365 alpha=0.05 id=date1 interval=day printall;
	run;
quit;

ods select all;

%accuracy(indsn=mintempavgprice, timeid=date1, series=avgprice, 
numholdback=&nhold);
run;

proc delete data=Work.preProcessedData;
run;